language: java

notifications:
  email: false
  irc:
    channels:
  	  - "irc.esper.net#MyTown"
    template:
      - "%{repository_name} (%{branch}): %{commit_message} - %{author}"
      - "Result: %{result}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"

deploy:
  provider: releases
  api_key:
    secure: GFJyjvU0SV+xS8Vhl5//eizgSCZjjzASJaIMfV88Znle8pR3zF8lpzQmnj7sgV8l9LY5LLWwhJfz1ci4GvcBYDJPvW4fuqKTPstw+EKrJ9ZDwFsQFFTzlsgzeYdWOK2jzrQdI0854StKOc4+AxIFM9hkk0VXFsp1EJ1EyUyfTbs=
  file: Libs/MyTown*
  skip_cleanup: true
  on:
  	tags: true
  	all_branches: true
    repo: legobear154/MyTown2

# Need to add a way to generate blog post, commands page, and changelogs after deployment and upload to gh_pages branch of project